### ISSUE TITLE
Generate MTA deployment descriptor fails

### ISSUE THREAD

**Issue by janestrong** [SAP-samples/extension-suite-learning-journey#1]
In chapter Manual deployment, Task 7: Generate an MTA Deployment Descriptor (mta.yaml), **mbt build -t ./** runs into error when executing command:

...ERROR the "before-all"" build failed: could not execute the **"npx -p @sap/cds-dk cds build --production"** command: exit status 1
make: *** [Makefile_20220606094941.mta:28: pre_build] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20220606094941.mta p=cf mtar= strict=true mode= t=\"./\"" command: exit status 2....

Additionally, the gen/db folder disappears when deploying with MTA.

**Comment by aancos** [comment]
me too!

**Comment by nuprivi** [comment]
Hello, @janestrong, @aancos this problem was solved for me using the post from [[christianjianelli](https://github.com/christianjianelli)](https://github.com/SAP-samples/extension-suite-learning-journey/issues/7)

**Comment by janestrong** [comment]
> Hello, @janestrong, @aancos this problem was solved for me using the post from [[christianjianelli](https://github.com/christianjianelli)](#7)

it worked using that solution, thank you!
