### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by vran848115** [SAP-samples/extension-suite-learning-journey#3]
Hi Team,

Referring this :- https://learning.sap.com/learning-journey/developing-with-sap-extension-suite/adding-an-external-service.
I have set apikey in .env file of my capm project.
Api Key has been copied from Business Partner A2X API of SAP API Business HUB portal.

**However when consuming, "connect to API_BUSINESS_PARTNER > odata {
  url: 'https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER/'"**

**I am getting below error:-**

code: 'ERR_HTTP_INVALID_HEADER_VALUE',
  request: {
    method: 'GET',
    url: "/A_BusinessPartner?$select=BusinessPartner,LastName,FirstName&$filter=BusinessPartner%20eq%20'9980002245'&$top=1",
    headers: { accept: 'application/json,text/plain', apikey: undefined }
  },

{"fault":{"faultstring":"Failed to resolve API Key variable request.header.apikey","detail":{"errorcode":"steps.oauth.v2.FailedToResolveAPIKey"}}}

Please advise/help.
Vishwa Ranjan

**Comment by christianjianelli** [comment]
I had the same issue with the empty apikey when running locally. Restarting the `cds watch` solved the problem. Thank you.
