### ISSUE TITLE
401 Unauthorized error - CLD200 - perfroming a manual deployment Excercise

### ISSUE THREAD

**Issue by govindturka** [SAP-samples/extension-suite-learning-journey#8]
I am doing this exercise and I am able to do it all the way except last step where I click on business partner and I am supposed to see the business partner data from API hub sandbox environment. I am getting 401- unauthorized error. Then I recreated the whole exercise but no success. I can see my applications with route url in my BTP account and cf push also is success with instance running. I can stop , restart the application from CLI and from BTP account. I then checked my destination service connection and it gives me same authorization error that connection established but unauthorized response. When I test the service in API hub , the response comes back 200 OK and I can see the response so API is working fine there. I read some blogs and tried to pass API key different ways(other than mentioned in exercise, i verified as well with cf env risk-management-srv) and I tried some commands told in those blogs but no success. Can anyone please help? Can anyone give package.json code as well as it seems the excercise screenshots have some extra code but not sure. 

Step n: Open the browser tab with the running service. The BusinessPartners endpoint should now provide the data from the external service, the SAP API Business Hub sandbox environment.Try to open the other service endpoints. The corresponding data should appear. Just now, it is not stored in an SQLite database, but in your SAP HANA Cloud trial HDI Container.
[Error Screenshots.docx](https://github.com/SAP-samples/extension-suite-learning-journey/files/9220152/Error.Screenshots.docx)

**Comment by venkymachineni** [comment]
Hi @markushaug,
 Is this issue resolved ?
I am also facing same issue, Please provide a link to the solution.
I do not find solution here.

Thanks,
Venkatesh.

**Comment by markushaug** [comment]
Hi all,

NOTE: For new issues, please open post them into our [learning community](https://groups.community.sap.com/t5/sap-btp-learning-q-a/qa-p/SAP-BTP-Learningqanda-board).

Let me point out to this important change in the CAP July release: https://cap.cloud.sap/docs/releases/jun22#auth-by-default

After deploying your service to a production environment (e.g., Cloud Foundry on SAP BTP), "all CAP service endpoints are now authenticated by default regardless of the authorization model."

For the learning journey, you have to continue with the authorization chapter. Afterwards, please deploy it again.

BR,
Markus
